package ru.bssg.lottabyte.core.model.reference;

public enum ReferenceType {
    INDICATOR_TO_ENTITY_ATTRIBUTE,
    INDICATOR_TO_DATA_ASSET,
    BUSINESS_ENTITY_TO_ENTITY,
    PRODUCT_TO_DATA_ENTITY_ATTRIBUTE,
    PRODUCT_TO_INDICATOR,
    PRODUCT_TO_PRODUCT,
    PRODUCT_TO_PRODUCT_TYPE,
    PRODUCT_TO_PRODUCT_SUPPLY_VARIANT,
    PRODUCT_TO_DATA_ASSET,
    DATA_ENTITY_TO_BUSINESS_ENTITY,
    BUSINESS_ENTITY_TO_BUSINESS_ENTITY,
    BUSINESS_ENTITY_TO_BUSINESS_ENTITY_LINK,
    PRODUCT_TO_BUSINESS_ENTITY_LINK,
    INDICATOR_TO_BUSINESS_ENTITY_LINK,
    ENTITY_ATTRIBUTE_TO_ENTITY_ATTRIBUTE,
    BUSINESS_ENTITY_TO_ENTITY_ATTRIBUTE,

    INDICATOR_FORMULA_TO_INDICATOR,
    INDICATOR_FORMULA_TO_ENTITY,
    SAMPLE_PROPERTY_TO_META_COLUMN,
    META_DATABASE_TO_TASK,
    DOMAIN_TO_RECOMMENDED_ARTIFACT
    //INDICATOR_FORMULA_TO_ENTITY_ATTRIB
    ;

    private ReferenceType() {

    }
}
