spring.datasource.url=jdbc:postgresql://rc1b-dz11uryhb4s1zfem.mdb.yandexcloud.net:6432/glossaryDB
spring.datasource.username=dcam_owner
spring.datasource.password=dcam_ownerBssgTest123

lottabyte.api.url=https://localhost:3000
lottabyte.api.username=wftest@test1.ru
lottabyte.api.password=1234
lottabyte.api.language=en
lottabyte.api.token=UUUUUUU

org.quartz.threadPool.threadCount = 5

app.security.jwt.keystore-location=keys/keystore.jks
app.security.jwt.keystore-password=password
app.security.jwt.key-alias=jwtsigning
app.security.jwt.private-key-passphrase=password
app.jwtExpirationInMs=86400000
app.jwtSecret=JWTSuperSecretKey

server.port=8082

spring.datasource.test-while-idle=true
spring.datasource.validation-query=SELECT 1;
spring.datasource.time-between-eviction-runs-millis=60000