spring.datasource.url=jdbc:postgresql://158.160.9.96:7432/prodGlossaryDB
spring.datasource.host=158.160.9.96
spring.datasource.port=7432
spring.datasource.db=prodGlossaryDB
spring.datasource.username=pgbouncer
spring.datasource.password=GRvi45tJMVHLw79ECDp5Xjbt
spring.datasource.hikari.maxLifetime=600000
spring.cache.type=none
spring.jackson.serialization-inclusion=non_null
spring.jackson.default-property-inclusion=non_null

spring.datasource.hikari.minimum-idle=2

kubernetes.image=cr.yandex/crpif5tg4kf4mom5kbmh/pgdumpimg:latest
kubernetes.api-version=batch/v1
kubernetes.metadata.name=lottabyte-console-job
kubernetes.namespace=lotta-test
kubernetes.container.name=lottabyte-console-job-container
kubernetes.image-pull-policy=Always
kubernetes.volume-mount.name=share-volume
kubernetes.volume.name=share-volume
kubernetes.persistent-volume-claim-volume-source.claim-name=share-volume
kubernetes.restart-policy=Never
kubernetes.job.kind=Job
system.data.storage=share

elasticsearch.protocol=https
elasticsearch.host=elastic.bssg.ru
elasticsearch.port=443
elasticsearch.connect-timeout=5000
elasticsearch.socket-timeout=120000
elasticsearch.username=elastic
elasticsearch.password=pass
spring.main.allow-bean-definition-overriding=true

app.security.jwt.keystore-location=keys/keystore.jks
app.security.jwt.keystore-password=password
app.security.jwt.key-alias=jwtsigning
app.security.jwt.private-key-passphrase=password
app.jwtExpirationInMs=86400000
app.jwtSecret=JWTSuperSecretKey

service-endpoint=storage.yandexcloud.net
signing-region=ru-central1
secret-key=YCPBCXJdZDqMM6l1grSIbv17aIzlMH2C7aY4wYOT
public-key=YCAJEl8Uvyf1JfCPmZpS5znWw
bucket=lottabyte
external_bucket=buckets

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
storage_path=share

springdoc.swagger-ui.path=/coreapi-doc/
app.security.cors.origin=http://localhost:3000

#logging.level.org.springframework.jdbc.core = TRACE

management.endpoint.flowable.enabled=true

flowable.idm.app.admin.user-id=admin
flowable.idm.app.admin.password=test
flowable.idm.app.admin.first-name=admin
flowable.idm.app.admin.last-name=admin
flowable.common.app.idm-admin.user=admin
flowable.common.app.idm-admin.password=test

flowable.admin.app.security.encryption.credentials-i-v-spec=j8kdO2hejA9lKmm6
flowable.admin.app.security.encryption.credentials-secret-spec=9FGl73ngxcOoJvmL
flowable.database-schema=wf
