stages:
  - build
  - deploy

usermanagement_build:
  tags:
    - lottabyte
  stage: build
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://localhost:2375/
  image: cr.yandex/yc/metadata-token-docker-helper:0.2
  services:
    - docker:19.03.1-dind
    #- docker:dind
  script:
    - docker build ./usermanagement/ -t cr.yandex/crpif5tg4kf4mom5kbmh/usermanagement:gitlab-$CI_COMMIT_SHORT_SHA
    - docker push cr.yandex/crpif5tg4kf4mom5kbmh/usermanagement:gitlab-$CI_COMMIT_SHORT_SHA

usermanagement_deploy:
  tags:
    - lottabyte
  image: gcr.io/cloud-builders/kubectl:latest
  #image: cr.yandex/crpif5tg4kf4mom5kbmh/ubuntu:ukubectl
  stage: deploy
  script:
    - kubectl config set-cluster k8s --server="$KUBE_URL" --insecure-skip-tls-verify=true
    - kubectl config set-credentials gitlab-admin --token="$KUBE_TOKEN"
    - kubectl config set-context default --cluster=k8s --user=gitlab-admin
    - kubectl config use-context default
    #- kubectl cluster-info
    #- kubectl config current-context
    - sed -i "s/__VERSION__/gitlab-$CI_COMMIT_SHORT_SHA/" usermanagement/k8s.yaml
    - kubectl apply -f usermanagement/k8s.yaml
